### ISSUE TITLE
DFCs don't have any oracle text

### ISSUE THREAD

**Issue by snowskeleton** [EskoSalaka/mtgtools#21]
double-face cards don't have an `oracle_text` attribute. From Scryfall, cards have a `face` list attribute containing `oracle_text` (among others) for each face. I haven't checked what Gatherer does for these cases.

**Comment by EskoSalaka** [comment]
Yeah, for all the multifaced cards the `oracle_text` is in the `card_faces` attribute. The card objects should have this attribute

**Comment by snowskeleton** [comment]
Okay, `card_faces` is definitely the one I was looking for (expecting to find as `faces`). What do you think of having a special case for DFCs that combines the oracle text of each face into the base `oracle_text` attribute? Or even just the front face.

**Comment by EskoSalaka** [comment]
I would say its better to conform with scryfall since its a bit problematic to do an exception in the case of multiface cards. However, if its more convenient in your particular use case, this should be achievable with quite a straightforward script. You can quite handily change&save the fields of the cards in the database to your liking
