### ISSUE TITLE
Card lists are repeating cards

### ISSUE THREAD

**Issue by majones12** [EskoSalaka/mtgtools#22]
Hi - I'm an amateur, so it may be that I am doing something wrong.

I previously created the db using the `scryfall_bulk_update(bulk_type='all_cards')` method.

Now if I run the following commands:
```
>>> from mtgtools.MtgDB import MtgDB
>>> mtg_db = MtgDB('mtg_db.fs')
>>> scryfall_cards = mtg_db.root.scryfall_cards
>>> znr = scryfall_cards.where_exactly(set='znr')
>>> len(znr)
3685
```

Which is much larger than I expected (I think the set should have 408 cards).
```
>>> sorted_znr = znr.sorted(lambda card: card.collector_number)
>>> for i in range(10):
...    print(sorted_znr[i].name, sorted_znr[i].collector_number, sorted_znr[i].color_identity)
```
We get:
```
Allied Assault 1 ['W']
Allied Assault 1 ['W']
Allied Assault 1 ['W']
Allied Assault 1 ['W']
Allied Assault 1 ['W']
Allied Assault 1 ['W']
Allied Assault 1 ['W']
Allied Assault 1 ['W']
Allied Assault 1 ['W']
Allied Assault 1 ['W']
```

It's repeating the same card.  If I print top 30, I see 11 Allied Assault, then 11 Disenchant, ...

Am I doing something wrong here, or is there bug in the program?

Thanks,

Mike J.

P.S. Apologies if this is not the right way to reach out.

**Comment by majones12** [comment]
I think I might understand what happened - ZNR was printed in 11 languages.  I suspect "all_cards" returned a separate card object for each printed language.  Confirmed - if I change it to:
```
>>> znr = scryfall_cards.where_exactly(set='znr', lang='en')
>>> len(znr)
408
```

**Comment by majones12** [comment]
So it's not a defect - closing.

**Comment by EskoSalaka** [comment]
This is perfectly fine way to contact! :)

Hmm... When I try on my computer after the scryfall_bulk_update (new clean database), with znr = scryfall_cards.where_exactly(set='znr'), i get 408 cards, so only the eng language cards.

Maybe theres some difference with how the two update methods fetch cards.

Edit: I realized you selected the 'all_cards' type. This one indeed contains every other language card and possibly also some other stuff that i have no idea about. I actually tried this 'all_cards' type a while ago and i couldnt get it to work because the amount of cards is so big that it takes too long to update! How long did it take for you? I got a new computer now, so ill give it a try too...

One big downside of the kind of db and its structure is that it works well when the amount of cards is relatively low, like ~50k -100k or so. If it gets bigger, it starts to use a lot or memory because there currently are no handy indexes and no processing architecture or smart query engine like in sql databases for example. Every 'query' needs to scan the whole set of cards and hold it in memory, so its not the fastest either. I think it iis generally also really slow at committing changes in bulk if you start running low on memory.

If this ever becomes a problem for normal uses-cases, i would need to build a bunch of indexes (of like card names, lang, pow/toughness, color, etc.)  and implement a query method that uses these indexes without needing to do full 'table' scans.

**Comment by majones12** [comment]
Thanks for the reply, I figured it out and closed the issue.  'all_cards' creates a separate card for each language the card is printed in.

Cheers

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by majones12** [comment]
Actually didn't take that long to load (maybe 6 or 7 minutes, I didn't log the output), but I noticed the same thing (re memory and speed).  I'm trying to build an inventory management tool for mtg cards - so I want 'all_cards' - but I don't need all the information for every card.  I'm starting to work on a sqlite implementation that gets the data from Scryfall, but stores only a fraction of the available information per card.  Thanks for this though - a great reference.

**Comment by EskoSalaka** [comment]
For me it took about 20 minutes but i think this is because i only have 8 gb of memory and it went close to 100% usage, i guess with more memory it would be close to your result. Loading the objects from the db initially takes pretty long too, something like 30s and the memory usage is again gigantic so its def not great. Querying however takes about 0.5 seconds which is actually not as bad as i though.

Yeah, i would also say that in your case using something like sqlite and writing your own queries for whatever you need is much better, especially if you plan to use it for a web app.
