### ISSUE TITLE
[Question] How to specify card number when reading PCardList from file?

### ISSUE THREAD

**Issue by MickHardins** [EskoSalaka/mtgtools#6]
Hi, first of all, great work, this tool is amazing. 😃 
I was wondering if it is possible to specify card number when reading a list of cards, this would be useful when dealing with tokens that have multiple printing images and different number while mantaining the same name.
E.g. Servo tokens in Kaladesh

**Comment by EskoSalaka** [comment]
Hi there, thanks for comment, great to see that people find it useful!

So, let's see. There are indeed multiple different Servos in the Kaladesh tokens

```
mtg_db = MtgDB('mydata.fs')
sets = mtg_db.root.scryfall_sets
cards = mtg_db.root.scryfall_cards
kldt = sets.where(name='Kaladesh Tokens')[0]
kldt.pprint()
```
```
-------------------------------------------------------------------------------------------------
Card                                  Set    Type                                  Cost   Rarity
-------------------------------------------------------------------------------------------------
1 Beast                               tkld   Token Artifact Creature - Beast              common
1 Chandra, Torch of Defiance Emblem   tkld   Emblem - Chandra                             common
1 Nissa, Vital Force Emblem           tkld   Emblem - Nissa                               common
1 Servo                               tkld   Token Artifact Creature - Servo              common
1 Construct                           tkld   Token Artifact Creature - Construct          common
1 Thopter                             tkld   Token Artifact Creature - Thopter            common
1 Thopter                             tkld   Token Artifact Creature - Thopter            common
1 Energy Reserve                      tkld   Card                                         common
1 Construct                           tkld   Token Artifact Creature - Construct          common
1 Dovin Baan Emblem                   tkld   Emblem - Dovin                               common
1 Servo                               tkld   Token Artifact Creature - Servo              common
1 Servo                               tkld   Token Artifact Creature - Servo              common
1 Thopter                             tkld   Token Artifact Creature - Thopter            common
```

with collector numbers

```
print([servo.collector_number for servo in kldt.where(name='Servo')])
['4', '5', '6']
```
As a deck string this set would be 

```
print(kldt.deck_str())

// Creatures (9)
1 Beast [tkld]
1 Servo [tkld]
1 Construct [tkld]
1 Thopter [tkld]
1 Thopter [tkld]
1 Construct [tkld]
1 Servo [tkld]
1 Servo [tkld]
1 Thopter [tkld]
```

Now, if I understood your porblem correctly, when you try to read these kinds of lists with multiple different cards with the same name as a string you would end up with

```
cards.from_str("""
// Creatures (9)
1 Beast [tkld]
1 Servo [tkld]
1 Construct [tkld]
1 Thopter [tkld]
1 Thopter [tkld]
1 Construct [tkld]
1 Servo [tkld]
1 Servo [tkld]
1 Thopter [tkld]
""").pprint()

-------------------------------------------------------------------------
Card          Set    Type                                  Cost   Rarity
-------------------------------------------------------------------------
1 Beast       tkld   Token Artifact Creature - Beast              common
3 Servo       tkld   Token Artifact Creature - Servo              common
2 Construct   tkld   Token Artifact Creature - Construct          common
3 Thopter     tkld   Token Artifact Creature - Thopter            common
```

which is because only one (prob the first) of the three different Servos is returned.

At the moment there is no way to specify a certain collector's number in the deck string. The best you can do is manually switch to whichever Servo you prefer. 

However, there are quite a few similar cards with alternate arts in the same sets, so it makes sense to add this functionality for example in the following way:

```
cards.from_str("""
// Creatures (9)
1 Beast [tkld]
1 Servo [tkld 4]
1 Construct [tkld]
1 Thopter [tkld]
1 Thopter [tkld]
1 Construct [tkld]
1 Servo [tkld 5]
1 Servo [tkld 6]
1 Thopter [tkld]
""")
```
It's probably not that much of work, so i'll take a look during the next week!

**Comment by MickHardins** [comment]
You understood correctly. The problem arises only when reading from string, otherwise it's fine!

> It's probably not that much of work, so i'll take a look during the next week!

Great 😎 !

**Comment by EskoSalaka** [comment]
Btw, do you happen to know if every card has a collector number?

**Comment by MickHardins** [comment]
I'm not sure: when i was developing my app i was using mtgjson data and some sets hadn't a collector number, i don't know if scryfall removed this inconsistency with wotc data by adding a number even if not officially present.

**Comment by MickHardins** [comment]
Ok. I checked some of the sets for which collector numbers were not available and it seems that scryfall has the data. 
So even if not 100% sure, its very likely that each card has a cpollector number 😄

**Comment by EskoSalaka** [comment]
Alright, I added the ability to specify the collector number of the card in the following way:
```

cards.from_str("""
// Creatures (9)
1 Beast [tkld 1]
1 Servo [tkld 4]
1 Construct [tkld]
1 Thopter [tkld]
1 Thopter [tkld]
1 Construct [tkld]
1 Servo [tkld 5]
1 Servo [tkld 6]
1 Thopter [tkld]
""").pprint()

Unnamed card list created at 2019-06-14 13:07:43.494994 with a total of 9 cards
-------------------------------------------------------------------------
Card          Set    Type                                  Cost   Rarity
-------------------------------------------------------------------------
1 Beast       tkld   Token Artifact Creature - Beast              common
1 Servo       tkld   Token Artifact Creature - Servo              common
2 Construct   tkld   Token Artifact Creature - Construct          common
1 Servo       tkld   Token Artifact Creature - Servo              common
1 Servo       tkld   Token Artifact Creature - Servo              common
3 Thopter     tkld   Token Artifact Creature - Thopter            common
```

Now you can choose which one you like but with the limitation that you first also specify the set!

I can't be bothered to write more tests so let's hope i didn't break anything :D

**Comment by MickHardins** [comment]
Hi! I did some test and something seems to go wrong. I have this list:

- 1 timetwister [ovnt 2]
- 1 Servo [tkld 4]
- 1 timetwister [ovnt 1]
- 1 Servo [tkld 3]
- 1 Servo [tkld 2]

This is the output i get: 
`UserWarning: Could not find any cards matching the line --1 timetwister [ovnt 2]-- with given keyword arguments --[]--.
                    This could possibly be because of a typo or because there are no cards matching the given keyword 
                    arguments or collector number if any were specified.`

The same is for each Servo 😭 

Also, it gives me some warning: 
`/Users/mick/.pyenv/versions/3.7.2/lib/python3.7/site-packages/mtgtools/MtgDB.py:254: UserWarning: This method is currently deprecated. The method "scryfall_update" is automatically called instead"`

**Comment by EskoSalaka** [comment]
Alright, lets see, hmm.

Firstly, the warning 
`/Users/mick/.pyenv/versions/3.7.2/lib/python3.7/site-packages/mtgtools/MtgDB.py:254: UserWarning: This method is currently deprecated. The method "scryfall_update" is automatically called instead"`
simply comes from the fact that i have depraceted the methods `update_new_from_scryfall` and `full_update_from_scryfall`. Now theres only the method `scryfall_update` which basically does a full update. This was because it turned out a bit too problematic to just fetch the new cards.

For the other problem, I think you are using the incorrect collector numbers! For example, there are no Servos with collector numbers 2 or 3. Take a look at the Scryfall page for the Kaladesh Tokens (TKLD)-set https://scryfall.com/sets/tkld. You can see that the servos have the collector numbers 4, 5 and 6. For example, for this servo https://img.scryfall.com/cards/large/en/tkld/5.jpg?1517813031 it is 5!

However, for the set Vintage Championship (OVNT) https://scryfall.com/sets/ovnt the collector numbers are quite weird!

```
ovnt = sets.where(code='ovnt')[0]

for card in ovnt:
    print(card, card.collector_number)

Black Lotus (ovnt) 2003
Timetwister (ovnt) 2004
Ancestral Recall (ovnt) 2005
Mox Pearl (ovnt) 2006
Mox Jet (ovnt) 2007
Mox Ruby (ovnt) 2008
Mox Emerald (ovnt) 2009
Mox Sapphire (ovnt) 2010
Time Walk (ovnt) 2011
Timetwister (ovnt) 2012
Ancestral Recall (ovnt) 2013
Mox Pearl (ovnt) 2014
Mox Emerald (ovnt) 2015
Mox Jet (ovnt) 2016EU
Mox Sapphire (ovnt) 2016NA
Mox Ruby (ovnt) 2017EU
Black Lotus (ovnt) 2017NA
Ancestral Recall (ovnt) 2018
Timetwister (ovnt) 2018A
Time Walk (ovnt) 2018NA
```

Im not sure about the logic of those, those numbers are not actually printed on the cards! These are maybe something decided by scryfall. Tbh, that set is kinda weird anyways.

As for your list, this works for me:

```
    1 timetwister [ovnt 2004]
    1 Servo [tkld 4]
    1 timetwister [ovnt 2018A]
    1 Servo [tkld 5]
    1 Servo [tkld 6]
```

If the collector numbers are no clearly visible on the cards, then you can always do the same check as i did with the ovnt cards above, or you can check directly the scryfall api objects, for example here https://api.scryfall.com/cards/search?order=set&q=e%3Aovnt&unique=prints. From there you can se that for example for the first Black Lotus the collector number is 2003. 

Try it and see if it works!

**Comment by MickHardins** [comment]
My bad, i uncorrectly thought that since there was a #4 servo, there were als #3 and less. 
Everything is working perfectly. 
Sorry for the mistake 😄 , will report back if i find errors.
Thanks!

**Comment by EskoSalaka** [comment]
Great, let's hope there's no more suprises!
