### ISSUE TITLE
Unable to fetch card images

### ISSUE THREAD

**Issue by MickHardins** [EskoSalaka/mtgtools#8]
Seems that scryfall has changed something, and now trying to download images results in a 403 code... 
```
Loading decklist file from tokens-cube.txt...
Building decklist...
Creating proxies in directory generated_pages/...
// Creatures (4)
4 Vampire [txln]


Something went wrong with downloading an image for Vampire (txln) from Scryfall: 
HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "proxyprint.py", line 654, in <module>
    main()
  File "proxyprint.py", line 647, in main
    create_pdf_proxies_unspaced(cards, output_dir, file_names=args.file_name)
  File "proxyprint.py", line 365, in create_pdf_proxies_unspaced
    for image in images:
TypeError: 'NoneType' object is not iterable
```

EDIT: I forced a database update, and the problem is gone. Probably they changed some links because of new card/set.

**Comment by EskoSalaka** [comment]
Yep. Hehe, the other day i was debugging the same thing and after like 2 hours i noticed that Scryfall changed the scheme for the card image url's. Took so much time to debug because some of the cards in my database had the new correct image links and some had the old one which return 403. Should be fine after an update
